=== wguttmann/GK-Custom-Mercaderia/custom/parameter/client/reports/es_CO/template.dtd
<?xml version="1.0" encoding="UTF-8"?>

  <!ELEMENT TEMPLATE (CHANGES_HISTORY?, PAGE_INFO, IMPORT_VARIABLES*, CONSTANT*, VARIABLE*, SECTION+)>
  <!ATTLIST TEMPLATE
  name CDATA #REQUIRED
  type (character|graphic) #REQUIRED
  version CDATA #REQUIRED
  created CDATA #REQUIRED
  author CDATA #REQUIRED
  comment CDATA #IMPLIED
  printer_name CDATA #IMPLIED
  project_name CDATA #IMPLIED
  >

  <!ELEMENT VARIABLES (IMPORT_VARIABLES*, CONSTANT*, VARIABLE*)>
  <!ATTLIST VARIABLES
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  created CDATA #REQUIRED
  author CDATA #REQUIRED
  comment CDATA #IMPLIED
  printer_name CDATA #IMPLIED
  project_name CDATA #IMPLIED
  >

  <!ELEMENT IMPORT_VARIABLES EMPTY>
  <!ATTLIST IMPORT_VARIABLES
  file CDATA #REQUIRED>

  <!ELEMENT CHANGES_HISTORY (CHANGE*)>

  <!ELEMENT CHANGE (#PCDATA)>
  <!ATTLIST CHANGE
  date CDATA #REQUIRED
  author CDATA #REQUIRED
  modified CDATA #REQUIRED>

  <!ELEMENT PAGE_INFO EMPTY>
  <!ATTLIST PAGE_INFO
  resolution CDATA #REQUIRED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
  top_margin CDATA #REQUIRED
  bottom_margin CDATA #REQUIRED
  left_margin CDATA #REQUIRED
  right_margin CDATA #REQUIRED
  standard_font CDATA #REQUIRED
  orientation (portrait|landscape) #IMPLIED>

  <!ELEMENT SECTION (VARIABLE*, ENTRY*)>
  <!ATTLIST SECTION
  id CDATA #REQUIRED
  type (header|footer|detail|firstpage-header|lastpage-footer) #REQUIRED
  condition CDATA #IMPLIED
  preferred_height CDATA #REQUIRED
  section_repeat CDATA #IMPLIED
  standard_font CDATA #IMPLIED
  color CDATA #IMPLIED
  border CDATA #IMPLIED
  matrix_mode (true|false) 'false'
  can_split (true|false) 'false'
  extended_borders (true|false) 'false'
  new_page_after (true|false) 'false'>

  <!ELEMENT VARIABLE EMPTY>
  <!ATTLIST VARIABLE
  name CDATA #REQUIRED
  datatype CDATA #REQUIRED
  argument CDATA #REQUIRED>

  <!ELEMENT CONSTANT EMPTY>
  <!ATTLIST CONSTANT
    name CDATA #REQUIRED
    datatype CDATA #REQUIRED
    argument CDATA #REQUIRED>

  <!ELEMENT ENTRY (PARAMETER*)>
  <!ATTLIST ENTRY
  id CDATA #REQUIRED
  type (label|variable|datafield|expression|query|line|barcode) #REQUIRED
  condition CDATA #IMPLIED
  argument CDATA #IMPLIED
  sample_value CDATA #IMPLIED
  datatype CDATA #IMPLIED
  representation CDATA #IMPLIED
  display_mask CDATA #IMPLIED
  domain CDATA #IMPLIED
  posX CDATA #REQUIRED
  posY CDATA #REQUIRED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
  font CDATA #IMPLIED
  alignmentH (left|center|right) 'left'
  alignmentV (top|middle|bottom) 'top'
  color CDATA #IMPLIED
  bgColor CDATA #IMPLIED
  underline (true|false) 'false'
  wrap (true|false) 'false'
  wrap_style (default|forced) #IMPLIED
  can_expand (true|false) 'false'>

  <!ELEMENT PARAMETER EMPTY>
  <!ATTLIST PARAMETER
  name CDATA #REQUIRED
  datatype CDATA #REQUIRED
  value CDATA #REQUIRED>

=== wguttmann/GK-Custom-Mercaderia/custom/parameter/client/reports/es_CO/transaction-preview-c-w44.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEMPLATE SYSTEM "template.dtd">

<TEMPLATE author='M5 team' created='20.05.2014' name='transaction-preview' version='1.0' type='character'>
  <CHANGES_HISTORY/>
  <PAGE_INFO resolution='1' width='44' height='2048' top_margin='0' bottom_margin='0' left_margin='0' right_margin='0' standard_font='NORMAL, PLAIN, -1'/>

  <!-- GLOBAL VARIABLES -->
  <!-- TODO: move to separate variables XML file -->
  <!-- Note: using StrFormat the %-sign need to be escaped by another %-sign! -->

  <!-- POSITIONS-->

  <!-- SALE RETURN LINE ITEMS -->

  <!-- SECTIONS FOR VOIDED LINE ITEMS  -->
  <SECTION id='1102' condition='TS.SALE_RETURN_LINE_ITEM.VOID_TYPE_CODE == "00"' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0'>
    <ENTRY id='lbl_void'           type='label'     argument='${lbl_voiding_reasoncode.VALI}' representation='character-text' posX='0'  posY='0' width='248'  height='1' alignmentH='left'  alignmentV='top' underline='true' color="rgb(130,13,202)"/>
  </SECTION>
  <SECTION id='1103' condition='TS.SALE_RETURN_LINE_ITEM.VOID_TYPE_CODE == "01"' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0'>
    <ENTRY id='lbl_void'           type='label'     argument='${lbl_voiding_reasoncode.VLLI}' representation='character-text' posX='0'  posY='0' width='248'  height='1' alignmentH='left'  alignmentV='top' underline='true' color="rgb(130,13,202)"/>
  </SECTION>

  <!-- SECTIONS FOR NON_VOIDED RETURNED LINE ITEMS -->
  <SECTION id='1111' condition='TS.SALE_RETURN_LINE_ITEM.RETURN_LINE AND TS.SALE_RETURN_LINE_ITEM.RETURN_TYPE AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND !TS.SALE_RETURN_LINE_ITEM.NEGATIVE_LINE_ITEM_FLAG' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0'>
    <ENTRY id='lbl_retoure'           type='label'     argument='${lbl_retoure}' representation='character-text' posX='0'  posY='0' width='248'  height='1' alignmentH='left'  alignmentV='top' underline='true'/>
  </SECTION>

  <!-- SECTIONS FOR VOIDED RETURNED LINE ITEMS  -->
  <SECTION id='1121' condition='TS.SALE_RETURN_LINE_ITEM.RETURN_LINE AND TS.SALE_RETURN_LINE_ITEM.RETURN_TYPE AND TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND !TS.SALE_RETURN_LINE_ITEM.NEGATIVE_LINE_ITEM_FLAG' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0' standard_font='STRIKETHROUGH, PLAIN, -1'>
    <ENTRY id='lbl_retoure'           type='label'     argument='${lbl_retoure}' representation='character-text' posX='0'  posY='0' width='248'  height='1' alignmentH='left'  alignmentV='top' underline='true' color="rgb(130,13,202)"/>
  </SECTION>

  <!-- SALE RETURN LINE ITEMS -->
  <!-- standard item name and total -->
  <!-- POS ITEM ID - ART/EAN -->
  <SECTION id='1231' condition='!TS.SALE_RETURN_LINE_ITEM.RETURNED AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND !Equals(TS.SALE_RETURN_LINE_ITEM.POS_ITEM_ID,NULL)' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0' standard_font='NORMAL, PLAIN, -1'>
    <ENTRY id='lbl_artno'       type='query'     argument='StrCat(${lbl_artno.argument}," ",TS.SALE_RETURN_LINE_ITEM.POS_ITEM_ID)' representation='character-text' posX='0'  posY='0' width='246'  height='1' alignmentH='left'  alignmentV='top' underline='false'/>
  </SECTION>
  <!-- LINE ITEM -->
  <SECTION id='1241' condition='!TS.SALE_RETURN_LINE_ITEM.RETURNED AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG' type='detail' preferred_height='2' section_repeat='1' new_page_after='false' border='0' standard_font='NORMAL, BOLD, 15'>
    <!-- standard layout -->
    <ENTRY id='fld_item_name'    condition='!Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.RECEIPT_TEXT'         datatype='java.lang.String' representation='character-text' posX='0'  posY='0' width='190' height='1' alignmentH='left'  alignmentV='top' sample_value='' display_mask=''            wrap='false' can_expand='false' underline='false'/>
    <ENTRY id='fld_bc_isocode'   condition='!Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='datafield'  argument='BS.CURRENCY_DATA.BASE_CURRENCY_CODE' representation='character-text' posX='189'  posY='0' width='37'  height='1' alignmentH='left'  alignmentV='top' underline='false'/>
    <ENTRY id='fld_item_total'   condition='!Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.SIGNED_AMOUNT'        datatype='java.lang.Double' representation='character-text' posX='233' posY='0' width='83' height='1' alignmentH='right' alignmentV='top' sample_value='' display_mask='ID:PRICE' wrap='false' can_expand='false' underline='false'/>
    <ENTRY id='lbl_x'            condition='!Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO") AND !TS.SALE_RETURN_LINE_ITEM.DISCOUNT_FLAG'        type='label'     argument='*'                                                  representation='character-text' posX='316'  posY='0' width='10'  height='1' alignmentH='left'  alignmentV='top'                                                                            underline='false'/>
    <ENTRY id='lbl_t'            condition='!Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='datafield'     argument='TS.SALE_RETURN_LINE_ITEM.TAX_RECEIPT_PRINT_CODE'                                                  representation='character-text' posX='326'  posY='0' width='10'  height='1' alignmentH='left'  alignmentV='top'                                                                            underline='false'/>
    <ENTRY id='lbl_f'            condition='BS.SYSTEM.US_PRINTOUT AND !Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO") AND !TS.SALE_RETURN_LINE_ITEM.RETURNED AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND TS.SALE_RETURN_LINE_ITEM.ALLOW_FOOD_STAMP_FLAG' type='label'  argument='F'  representation='character-text' posX='336'  posY='0' width='16'  height='1' alignmentH='left'  alignmentV='top'  underline='false'/>
    <!-- sales order layout -->
    <ENTRY id='fld_item_name'    condition='Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.RECEIPT_TEXT'         datatype='java.lang.String' representation='character-text' posX='0'  posY='0' width='190' height='1' alignmentH='left'  alignmentV='top' sample_value='' display_mask=''            wrap='false' can_expand='false' underline='false'/>
    <ENTRY id='fld_bc_isocode'   condition='Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'      type='datafield'  argument='BS.CURRENCY_DATA.BASE_CURRENCY_CODE' representation='character-text' posX='189'  posY='0' width='37'  height='1' alignmentH='left'  alignmentV='top' underline='false'/>
    <ENTRY id='fld_item_total'   condition='Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO")'     type='query' argument='StrCat("(",Format(TS.SALE_RETURN_LINE_ITEM.SIGNED_AMOUNT,ID:PRICE),")")'        datatype='java.lang.Double' representation='character-text' posX='233' posY='0' width='83' height='1' alignmentH='right' alignmentV='top' sample_value='' display_mask='' wrap='false' can_expand='false' underline='false'/>
    <ENTRY id='lbl_x'            condition='Equals(TS.SALE_RETURN_LINE_ITEM.ITEM_TYPE,"SO") AND !TS.SALE_RETURN_LINE_ITEM.DISCOUNT_FLAG'        type='label'     argument='*'                                                  representation='character-text' posX='316'  posY='0' width='10'  height='1' alignmentH='left'  alignmentV='top'                                                                            underline='false'/>
  </SECTION>
  <SECTION id='1242' condition='!TS.SALE_RETURN_LINE_ITEM.RETURNED AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND TS.SALE_RETURN_LINE_ITEM.HAS_RECEIPT_TEXT_ALTERNATIVE' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0'>
    <ENTRY id='fld_item_name_alt'         type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.RECEIPT_TEXT_ALTERNATIVE.TEXT'         datatype='java.lang.String' representation='character-text' posX='0'  posY='0' width='246' height='1' alignmentH='left'  alignmentV='top' sample_value='' display_mask=''            wrap='false' can_expand='false' underline='false'/>
  </SECTION>
  <!-- QUANTITY -->
  <SECTION id='1244' condition='!TS.SALE_RETURN_LINE_ITEM.HAS_ORDER_INFORMATION AND !TS.SALE_RETURN_LINE_ITEM.RETURNED AND !TS.SALE_RETURN_LINE_ITEM.VOID_FLAG AND (!TS.SALE_RETURN_LINE_ITEM.SINGLE_QUANTITY OR TS.SALE_RETURN_LINE_ITEM.QUANTITY_INPUT_METHOD_TYPE_OTHER) AND !TS.SALE_RETURN_LINE_ITEM.QUANTITY_INPUT_METHOD_TYPE_WEIGHT' type='detail' preferred_height='1' section_repeat='1' new_page_after='false' border='0' standard_font='NORMAL, PLAIN, -1'>
    <!--ENTRY id='fld_item_quantity'     type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.SIGNED_QUANTITY_MULTIPLIED_UNITS'     datatype='java.lang.Double' representation='character-text' posX='6'  posY='0' width='100'  height='1' alignmentH='right' alignmentV='top' sample_value='' display_mask='ID:QUANTITY'    wrap='false' can_expand='false' underline='false'/>
    <ENTRY id='lbl_x_quantity'        type='label'     argument='${lbl_x_quantity}'                                                  representation='character-text' posX='120'  posY='0' width='16'  height='1' alignmentH='left'  alignmentV='top'                                                                            underline='false'/>
    <ENTRY id='fld_item_single_price' type='datafield' argument='TS.SALE_RETURN_LINE_ITEM.SINGLE_PRICE' datatype='java.lang.Double' representation='character-text' posX='136'  posY='0' width='96' height='1' alignmentH='right' alignmentV='top' sample_value='' display_mask='ID:PRICE' wrap='false' can_expand='false' underline='false'/>
